# Generated by Django 4.0.4 on 2022-07-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_name_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
